import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/globals.css";
import "./css/preview_mark_down.css";
import "./css/style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Trang Chủ",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <meta
                name="google-site-verification"
                content="6VLnuCRKAL_sVhqRoOlO4HzmYjf78guJEXX-pOfu3UA"
            />
            <body className={inter.className}>{children}</body>
        </html>
    );
}
